### ISSUE TITLE
Add API connections to match a show with a streaming service BACKEND

### ISSUE THREAD

**Issue by mpicazocp** [mpicazocp/BoxOffice#19]

**Comment by IgalTam** [comment]
Use ts/js with REST API and streaming APIs to determine the available platform(s) for media in the database.

TE: 3 hours

**Comment by crobin27** [comment]
Abandoned issue -> Ran into many brick walls attempting to work with multiple api's at once
- With more time this would have been a great implementation as the search would show the streaming service as well
- Substituted this with the IMDB API to query Name, Description, and Image (Success!)
